spring:
  application:
    name: java-graphql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java-graphql
    username: java-graphql
    password: java-graphql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
  graphql:
    graphiql:
      enabled: true